services:
  app:
    build: .
    container_name: coffee_shop_app
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: coffee_shop_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

  redis:
    image: redis:7
    container_name: coffee_shop_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: coffee_shop_rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

volumes:
  pgdata:
  redisdata: